src/answer/urls.py
from .views import QuestionListView, QuestionDetailView, AnswerByMeListView, MyQuestionView, MyUpvoteView, \
    QuestionOfTheSiteView, QuestionOfTheHour

from django.conf.urls import url

urlpatterns = [
    url(r'^$', QuestionListView.as_view(), name='home'),
    url(r'^(?P<pk>\d+)/$', QuestionDetailView.as_view(), name='detail'),
    url(r'^myanswers/$', AnswerByMeListView.as_view(), name='my_answers'),
    url(r'^myquestions/(?P<pk>\d)/$', MyQuestionView.as_view(), name='my_questions'),
    url(r'^myupvotes/$', MyUpvoteView.as_view(), name='my_upvotes'),
    url(r'^questionofthesite/$', QuestionOfTheSiteView.as_view(), name='question_of_the_site'),
    url(r'questionofthehour/$', QuestionOfTheHour.as_view(), name='question_of_the_hour')
]

src/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LoginView,LogoutView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^question/', include('answer.urls', namespace='answer')),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout')

]

src/answer/models.py
from django.contrib.auth.models import User
from django.db import models
from django.shortcuts import reverse


# Create your models here.

class Question(models.Model):
    user = models.ForeignKey(User)
    title = models.CharField(max_length=200, blank=True, null=True)
    description = models.TextField()
    pub_date = models.DateTimeField()

    def __str__(self):
        return self.title


class Answer(models.Model):
    answer_text = models.TextField()
    questions = models.ForeignKey(Question)
    pub_date = models.DateTimeField(auto_now_add=True)
    # upvote = models.IntegerField(null=True, blank=True)
    user = models.ForeignKey(User)

    def __str__(self):
        return self.answer_text

    def get_absolute_url(self):
        return reverse('answer:answer_by_me', kwargs={'pk': self.user.id})


class Upvote(models.Model):
    user = models.ForeignKey(User)
    answers = models.ForeignKey(Answer)

    def __str__(self):
        return self.user.username

src/answer/views.py
from datetime import timedelta
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import ListView, DetailView, TemplateView
from django.contrib.auth.views import LoginView

from .models import Question, Answer, Upvote


class QuestionListView(ListView):
    model = Question


class QuestionDetailView(DetailView):
    model = Question
    context_object_name = 'question'

    def post(self, request, *args, **kwargs):
        print(request.POST)
        if request.POST['type'] == 'vote':
            ans = Answer.objects.get(id=request.POST['answer_id'])
            if request.user.is_authenticated:
                if request.POST['vote'][0:1] == 'U':
                    upvote = Upvote.objects.get_or_create(answers=ans, user=request.user)
                elif request.POST['vote'][0:1] == 'D':
                    upvote = Upvote.objects.filter(answers=ans, user=request.user).delete()

            # if not logged in
        return HttpResponseRedirect(f'/question/{ans.questions.id}')


# class AnswerByMeListView(ListView):
#     template_name = 'answer/myanswer.html'
#
#     def get_queryset(self):
#         print(Answer.objects.filter(user=self.request.user))
#         return Answer.objects.filter(user=self.request.user)
#
#     # def my_answer(self):
#     #     print(self.get_context_data())
#     #     return Answer.objects.filter(user=self.request.user)
#     #
#

class AnswerByMeListView(LoginRequiredMixin, ListView):
    model = Answer
    template_name = 'answer/myanswer.html'
    login_url = '/login'
    redirect_field_name = 'next'

    # def get_context_data(self, **kwargs):
    #     context = super(AnswerByMeListView, self).get_context_data(**kwargs)
    #     context['pk'] = self.kwargs['pk']
    #     return context

    def get_queryset(self):
        return Answer.objects.filter(user=self.request.user)


class MyQuestionView(LoginRequiredMixin, TemplateView):
    template_name = 'answer/myquestions.html'

    def my_question(self):
        return Question.objects.filter(user=self.request.user)


class MyUpvoteView(LoginRequiredMixin, TemplateView):
    template_name = 'answer/my_upvotes.html'

    def my_upvotes(self):
        return Upvote.objects.filter(user=self.request.user)


class QuestionOfTheHour(LoginRequiredMixin, TemplateView):
    template_name = 'answer/question_of_the_hour.html'

    def question_of_the_hour(self):
        last_hour_questions = Answer.objects.filter(pub_date__gte=timezone.now() - timedelta(hours=1))
        best_question = last_hour_questions[0]
        old_vote = 0
        for ans in best_question.answer_set.all():
            old_vote += ans.upvote_set.all().count()

        for question in Question.objects.all():
            vote = 0
            for ans in question.answer_set.all():
                vote += ans.upvote_set.all().count()
            if vote > old_vote:
                best_question = question
        return best_question


class QuestionOfTheSiteView(LoginRequiredMixin, TemplateView):
    template_name = 'answer/question_of_the_site.html'

    def question_of_the_site(self):
        best_question = Question.objects.first()
        old_vote = 0
        for ans in best_question.answer_set.all():
            old_vote += ans.upvote_set.all().count()

        for question in Question.objects.all():
            vote = 0
            for ans in question.answer_set.all():
                vote += ans.upvote_set.all().count()
            if vote > old_vote:
                best_question = question
        return best_question

src/accounts/templates/accounts/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

src/accounts/templates/accounts/profileedit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

src/answer/templates/answer/my_upvotes.html
{% extends 'base.html' %}
{% block title %} {% endblock %}

{% block body %}
    <div class="container-fluid">
        {% for upvote in view.my_upvotes %}
            <a href="{% url 'answer:detail' upvote.answers.questions.pk %}"
               class="list-group-item">{{ upvote.answers }}</a>
        {% empty %}
            <p>You have not upvoted any anwer yet.</p>
        {% endfor %}
    </div>
{% endblock %}

src/answer/templates/answer/myanswer.html
{% extends 'base.html' %}

{% block body %}
    <h1 class="jumbotron" style="text-align: center">Welcome To Q & A site </h1>
    <style>
        .list-group a.list-group-item:hover {
            background-color: #6bb7bb;
        }

    </style>

    <div class="container-fluid">
        <h2> Question List Answered By Me </h2>
        <div class="list-group">
        {{ request.user }}
            {% for answer in object_list %}

                <a href="{% url 'answer:detail' answer.questions.id %}" class="list-group-item">
                <b>{{ answer.questions.user }}</b>:: &nbsp; {{ answer.questions.title }}
                </a>

                <a href="{% url 'answer:detail' answer.questions.id %}" class="list-group-item ">
                   Ans>> {{ answer.user }}:: &nbsp;{{ answer}}</a>
                <br>

                {% empty %}
                    <p> You have not answered any!</p>
            {% endfor %}

        </div>
    </div>


{% endblock %}

src/answer/templates/answer/myquestions.html
{% extends 'base.html' %}
{% block title %} {% endblock %}
{% block body %}
    <div class="container-fluid">
        <h2>Question List </h2>
        <div class="list-group">
            {% for question in view.my_question %}
                <a href="{% url 'answer:detail' question.pk %}" class="list-group-item "
                   id="lst">{{ question.title }}</a>
                {% empty %}
                <p> You have not asked any question yet.</p>
            {% endfor %}

        </div>
    </div>
{% endblock %}

src/answer/templates/answer/question_detail.html
{% extends 'base.html' %}

{% block title %} {{ question.title }} {% endblock %}
{% load upvote_tags %}
{% block body %}
    <h3><i>{{ question.title }}</i></h3>
    {{ question.description }}
    {% for answer in question.answer_set.all %}
        <br>
        <div>
        <p>{{ answer.answer_text }} <span style="font-size: 15px">by [{{ answer.user }}]</span></p>
        <form method="post" action="{% url 'answer:detail' question.id %}">
            {% csrf_token %}
            <input type="hidden" name="type" value="vote">
            <input type="hidden" name="answer_id" value="{{ answer.id }}">

            {% if request.user.is_authenticated %}
                {% if request.user|has_upvoted:answer %}
                    <input type="submit" class="btn btn-warning" name='vote' value="Downvote|{{ answer.upvote_set.all.count }}">
                {% else %}
                    <input type="submit" class="btn btn-success" name='vote' value="Upvote|{{ answer.upvote_set.all.count }}">
                {% endif %}

            {% else %}
                <input type="submit" class="btn btn-danger" onclick="loginAlert()" value="Upvote|{{ answer.upvote_set.all.count }}">
            {% endif %}


        </form>

    {% endfor %}
<br>
<button type="button" class="btn btn-info" data-toggle="collapse" data-target="#answer"><span
        class="glyphicon glyphicon-pencil"></span> Answer
</button>
<form action="{% url 'answer:detail' question.id %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="type" value="answer">
    <input type="hidden" name="question_id" value="{{ question.id }}">
    <div id="answer" class="collapse">
        <div class="form-horizontal">
            <div class="form-group">
                <div class="col-md-9">
                    <textarea class="form-control" rows="6" placeholder="Write your answer here"
                              required name="write"></textarea>
                </div>
            </div>
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
    </div>
</form>
<script>
</script>
</div>
    <script>
        function loginAlert() {
            alert("Alert! Please Login To Vote");
            window.location = 'http://127.0.0.1:8000/login/';

        }

        function votedAlert() {
            alert("Alert! You already upvoted this answer");
        }
    </script>
{% endblock %}

src/answer/templates/answer/question_list.html
{% extends 'base.html' %}

{% block body %}
    <h1 class="jumbotron" style="text-align: center">Welcome To Q & A site </h1>
    <style>
        .list-group a.list-group-item:hover {
            background-color: #6bb7bb;
        }

    </style>

    <div class="container-fluid">
        <h2>Question List </h2>
        <div class="list-group">
            {% for question in object_list %}
                <a href="{% url 'answer:detail' question.pk %}" class="list-group-item "
                   id="lst">{{ question.title }}</a>
            {% endfor %}
        </div>
    </div>


{% endblock %}

src/answer/templates/answer/question_of_the_hour.html
{% extends 'base.html' %}

{% block title %} {% endblock %}

{% block body %}
    <div class="container-fluid">
        {% if views.question_of_the_hour %}
            Question of the hour : {{ view.question_of_the_hour }}
        {% else %}
            No Question Have Been submitted this hour
        {% endif %}

    </div>
{% endblock %}

src/answer/templates/answer/question_of_the_site.html
{% extends 'base.html' %}

{% block title %} {% endblock %}

{% block body %}
    <div class="container-fluid">
    Question of the site is : {{ view.question_of_the_site }}
    </div>
{% endblock %}

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}My Website {% endblock %}</title>
    <meta charset="utf-8">
    {% include 'snippets/css.html' %}
</head>
<body>

{% include 'snippets/nav.html'%}


{% block body %}
{% endblock %}


{% include 'snippets/js.html' %}

</body>

</html>

src/templates/snippets/css.html
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

src/templates/snippets/js.html
<!-- Latest compiled and minified JavaScript -->
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

src/templates/snippets/nav.html
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!--Logo -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mainNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{% url 'answer:home' %}" class="navbar-brand">MySite</a>
        </div>

        <div class="collapse navbar-collapse" id="mainNavBar">

            <ul class="nav navbar-nav">
                <li><a href="#">Home</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Contact</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">View Options <span
                            class="caret"></span> </a>
                    <ul class="dropdown-menu">
                        {% if user.is_authenticated %}
                            <li><a href="{% url 'answer:my_questions' pk=request.user.pk %}">My Questions</a></li>
                            <li><a href="{% url 'answer:my_answers' %}">My Answers</a></li>
                            <li><a href="{% url 'answer:my_upvotes' %}">My Upvotes</a></li>
                        {% endif %}
                        <li><a href="{% url 'answer:question_of_the_hour' %}">Question of the hour</a></li>
                        <li><a href="{% url 'answer:question_of_the_site' %}">Question of the site</a></li>
                    </ul>
                </li>
            </ul>


            <div class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li>{{ user }}<a href="{% url 'logout' %}"> Logout <span
                            class=" glyphicon glyphicon-log-out"></span></a></li>
                {% else %}

                    <li><a href="#">SignUp <span
                            class=" glyphicon glyphicon-registration-mark"></span></a></li>

                    <li><a href="{% url 'login' %}">Login <span
                            class=" glyphicon glyphicon-log-in"></span></a></li>
                {% endif %}
            </div>
        </div>

    </div>
</nav>